version: '3.8'

networks:
  rconfig6Network:
    driver: bridge

services:
  mariadb:
    image: mariadb:10.8
    container_name: rconfig6-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    expose:
      - 3306
    networks:
      - rconfig6Network

  php-apache:
    container_name: rconfig6-php-apache
    build:
      context: ./php
    ports:
      - '${EXPOSED_APP_PORT}:80'
    volumes:
      - ./src:/var/www/html/rconfig6
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - rconfig6Network

  cronjob:
    container_name: rconfig6-cronjob
    build:
      context: ./cron
    volumes:
      - ./src:/var/www/html/rconfig6
    restart: always
    networks:
      - rconfig6Network
    depends_on:
      - php-apache

  horizon:
    container_name: rconfig6-horizon-supervisor
    build:
      context: ./horizon
    expose:
      - 80
    volumes:
      - ./src:/var/www/html/rconfig6
    restart: always
    env_file: .env
    networks:
      - rconfig6Network
    depends_on:
      - php-apache

  redis:
    image: redis:alpine
    container_name: rconfig6-redis
    restart: unless-stopped
    expose:
      - 6379
    networks:
      - rconfig6Network
